version: "3"
services:
  slave:
    image: jenkins/jnlp-slave
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: slave
        awslogs-region: us-east-2
        awslogs-stream-prefix: slave_
